// ============== Copyright (c) 2025 Monochrome Games ============== \\

#ifndef SHARED_ZOMBIEPANIC_ACHIEVEMENTS
#define SHARED_ZOMBIEPANIC_ACHIEVEMENTS
#pragma once

enum EStats
{
	INVALID_STAT = -1,
	ZP_KILLS_CROWBAR = 0,
	ZP_KILLS_PISTOL,
	ZP_KILLS_REVOLVER,
	ZP_KILLS_RIFLE,
	ZP_KILLS_SHOTGUN,
	ZP_KILLS_SATCHEL,
	ZP_KILLS_TNT,
	ZP_KILLS_ZOMBIE,
	ZP_FLEEESH,
	ZP_ITS_A_MASSACRE,
	ZP_PANIC_100,
	ZP_PUMPUPSHOTGUN,
	ZP_CHILDOFGRAVE,
	ZP_KILLS_MP5,

	STAT_MAX
};

enum EAchievements
{
	ONE_OF_US = 0,
	FIRST_TO_DIE,
	PANIC_ATTACK,
	KILLS_PISTOL,
	KILLS_SHOTGUN,
	KILLS_RIFLE,
	KILLS_REVOLVER,
	KILLS_SATCHEL,
	KILLS_TNT,
	KILLS_CROWBAR,
	KILLS_ZOMBIE,
	YOU_WILL_DIE_WITH_ME,
	UNSAFE_HANDLING,
	I_FELL,
	FIRST_SURVIVAL,
	FIRST_OBJECTIVE,
	JACKOFTRADES,
	CLOCKOUT,
	PANICRUSH,
	FLEEESH,
	ZOMBIEDESSERT,
	SCREAM4ME,
	ITS_A_MASSACRE,
	THE_ATEAM,
	LASTMANSTAND,
	MARATHON,
	PARTNERINCRIME,
	RABBITBEAST,
	PLAY_ALL_SURVIVAL,
	PLAY_ALL_OBJECTIVE,
	PANIC_100,
	INLINEP2,
	PUMPUPSHOTGUN,
	CUTYOUDOWN,
	CHILDOFGRAVE,
	DIE_BY_DOOR,
	ZMASH,
	TABLE_FLIP,
	KILLS_MP5,
	PARTOFHORDE,

	ACHV_MAX
};

struct StatData_t
{
	EStats ID;
	const char *Name;
	int32 Value;
	int32 MaxValue;
};

#endif