// ============== Copyright (c) 2025 Monochrome Games ============== \\

#ifndef ZOMBIEPANIC_SHARED_WEAPON_H
#define ZOMBIEPANIC_SHARED_WEAPON_H

// Sig / Shared pistol animations
enum
{
	ANIM_PISTOL_IDLE1 = 0,
	ANIM_PISTOL_IDLE2,
	ANIM_PISTOL_IDLE3,
	ANIM_PISTOL_SHOOT,
	ANIM_PISTOL_SHOOT_EMPTY,
	ANIM_PISTOL_RELOAD,
	ANIM_PISTOL_RELOAD_EMPTY,
	ANIM_PISTOL_DRAW,
	ANIM_PISTOL_HOLSTER,
	ANIM_PISTOL_DRAW_EMPTY,
	ANIM_PISTOL_HOLSTER_EMPTY,
	ANIM_PISTOL_IDLE1_EMPTY,
	ANIM_PISTOL_IDLE2_EMPTY,
	ANIM_PISTOL_IDLE3_EMPTY
};

// Shotgun animations
enum
{
	ANIM_SHOTGUN_IDLE = 0,
	ANIM_SHOTGUN_IDLE2,
	ANIM_SHOTGUN_FIRE,
	ANIM_SHOTGUN_PUMP,
	ANIM_SHOTGUN_RELOAD_START,
	ANIM_SHOTGUN_RELOAD,
	ANIM_SHOTGUN_RELOAD_END,
	ANIM_SHOTGUN_DRAW,
	ANIM_SHOTGUN_HOLSTER,
};

// M16 / 5.56mm rifle animations
enum
{
	ANIM_AR556_LONGIDLE = 0,
	ANIM_AR556_IDLE1,
	ANIM_AR556_LAUNCH,
	ANIM_AR556_RELOAD,
	ANIM_AR556_DEPLOY,
	ANIM_AR556_FIRE1,
	ANIM_AR556_FIRE2,
	ANIM_AR556_FIRE3,
	ANIM_AR556_RELOAD_EMPTY,
	ANIM_AR556_HOLSTER
};

// MP5 / 9mm SMG animations
enum
{
	ANIM_MP5_LONGIDLE = 0,
	ANIM_MP5_IDLE1,
	ANIM_MP5_RELOAD,
	ANIM_MP5_DEPLOY,
	ANIM_MP5_FIRE1,
	ANIM_MP5_FIRE2,
	ANIM_MP5_FIRE3
};

// .357 / Magnum revolver animations
enum
{
	ANIM_357_IDLE1 = 0,
	ANIM_357_FIDGET,
	ANIM_357_FIRE1,
	ANIM_357_RELOAD,
	ANIM_357_HOLSTER,
	ANIM_357_DRAW,
	ANIM_357_IDLE2,
	ANIM_357_IDLE3
};

// Melee animations
enum
{
	ANIM_MELEE_IDLE1 = 0,
	ANIM_MELEE_DRAW,
	ANIM_MELEE_HOLSTER,
	ANIM_MELEE_ATTACK1MISS,
	ANIM_MELEE_ATTACK1HIT,
	ANIM_MELEE_ATTACK2MISS,
	ANIM_MELEE_ATTACK2HIT,
	ANIM_MELEE_ATTACK3MISS,
	ANIM_MELEE_ATTACK3HIT,
	ANIM_MELEE_IDLE2,
	ANIM_MELEE_IDLE3,
	ANIM_MELEE_HEAVY_HOLD,
	ANIM_MELEE_HEAVY_HIT,
	ANIM_MELEE_HEAVY_MISS
};

// Grenades and other thrown explosives
enum
{
	ANIM_THROW_EXPLOSIVES_IDLE = 0,
	ANIM_THROW_EXPLOSIVES_FIDGET,
	ANIM_THROW_EXPLOSIVES_PINPULL,
	ANIM_THROW_EXPLOSIVES_THROW,
	ANIM_THROW_EXPLOSIVES_PINPULL2,
	ANIM_THROW_EXPLOSIVES_THROW2,
	ANIM_THROW_EXPLOSIVES_HOLSTER,
	ANIM_THROW_EXPLOSIVES_DRAW
};


#endif